#!/usr/bin/env python3
"""
Generate Interactive HTML Histogram for Downtrend Duration Analysis

Creates Plotly.js-based interactive visualizations from downtrend analysis JSON data.
"""

from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime
from pathlib import Path
from typing import Any

# HTML template with embedded Plotly.js
HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Downtrend Duration Analysis</title>
    <script src="https://cdn.plot.ly/plotly-2.27.0.min.js"></script>
    <style>
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            margin: 0;
            padding: 20px;
            background: #f5f5f5;
        }}
        .container {{
            max-width: 1400px;
            margin: 0 auto;
            background: white;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }}
        h1 {{
            color: #333;
            margin-bottom: 10px;
        }}
        .subtitle {{
            color: #666;
            margin-bottom: 20px;
        }}
        .controls {{
            display: flex;
            gap: 20px;
            margin-bottom: 20px;
            flex-wrap: wrap;
        }}
        .control-group {{
            display: flex;
            flex-direction: column;
            gap: 5px;
        }}
        .control-group label {{
            font-weight: 600;
            color: #444;
            font-size: 14px;
        }}
        select {{
            padding: 8px 12px;
            border: 1px solid #ddd;
            border-radius: 4px;
            font-size: 14px;
            min-width: 150px;
        }}
        .stats-grid {{
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
            gap: 15px;
            margin-bottom: 20px;
        }}
        .stat-card {{
            background: #f8f9fa;
            padding: 15px;
            border-radius: 6px;
            text-align: center;
        }}
        .stat-value {{
            font-size: 24px;
            font-weight: 700;
            color: #2563eb;
        }}
        .stat-label {{
            font-size: 12px;
            color: #666;
            margin-top: 5px;
        }}
        #histogram {{
            width: 100%;
            height: 500px;
        }}
        #boxplot {{
            width: 100%;
            height: 300px;
            margin-top: 20px;
        }}
        .footer {{
            margin-top: 20px;
            padding-top: 15px;
            border-top: 1px solid #eee;
            font-size: 12px;
            color: #888;
        }}
    </style>
</head>
<body>
    <div class="container">
        <h1>Downtrend Duration Analysis</h1>
        <div class="subtitle">
            Analysis Date: {analysis_date} | Lookback: {lookback_years} years | Total Downtrends: {total_downtrends:,}
        </div>

        <div class="controls">
            <div class="control-group">
                <label for="sectorFilter">Sector</label>
                <select id="sectorFilter" onchange="updateCharts()">
                    <option value="all">All Sectors</option>
                    {sector_options}
                </select>
            </div>
            <div class="control-group">
                <label for="marketCapFilter">Market Cap</label>
                <select id="marketCapFilter" onchange="updateCharts()">
                    <option value="all">All Market Caps</option>
                    <option value="Mega">Mega ($200B+)</option>
                    <option value="Large">Large ($10B-$200B)</option>
                    <option value="Mid">Mid ($2B-$10B)</option>
                    <option value="Small">Small (<$2B)</option>
                </select>
            </div>
            <div class="control-group">
                <label for="binSize">Bin Size (days)</label>
                <select id="binSize" onchange="updateCharts()">
                    <option value="5">5 days</option>
                    <option value="10" selected>10 days</option>
                    <option value="15">15 days</option>
                    <option value="20">20 days</option>
                </select>
            </div>
        </div>

        <div class="stats-grid" id="statsGrid">
            <!-- Stats populated by JavaScript -->
        </div>

        <div id="histogram"></div>
        <div id="boxplot"></div>

        <div class="footer">
            Generated by Downtrend Duration Analyzer | Peak/Trough Window: {peak_window} days | Min Depth: {min_depth}%
        </div>
    </div>

    <script>
        // Embedded data
        const allDowntrends = {downtrends_json};

        function filterData() {{
            const sector = document.getElementById('sectorFilter').value;
            const marketCap = document.getElementById('marketCapFilter').value;

            return allDowntrends.filter(d => {{
                const sectorMatch = sector === 'all' || d.sector === sector;
                const capMatch = marketCap === 'all' || d.market_cap_tier === marketCap;
                return sectorMatch && capMatch;
            }});
        }}

        function computeStats(data) {{
            if (data.length === 0) return null;

            const durations = data.map(d => d.duration_days).sort((a, b) => a - b);
            const n = durations.length;

            const sum = durations.reduce((a, b) => a + b, 0);
            const mean = sum / n;
            const median = n % 2 === 0
                ? (durations[n/2 - 1] + durations[n/2]) / 2
                : durations[Math.floor(n/2)];

            const p25 = durations[Math.floor(n * 0.25)];
            const p75 = durations[Math.floor(n * 0.75)];
            const p90 = durations[Math.floor(n * 0.90)];

            return {{ count: n, mean, median, p25, p75, p90 }};
        }}

        function updateStats(stats) {{
            const grid = document.getElementById('statsGrid');
            if (!stats) {{
                grid.innerHTML = '<div class="stat-card"><div class="stat-value">-</div><div class="stat-label">No Data</div></div>';
                return;
            }}

            grid.innerHTML = `
                <div class="stat-card">
                    <div class="stat-value">${{stats.count.toLocaleString()}}</div>
                    <div class="stat-label">Downtrends</div>
                </div>
                <div class="stat-card">
                    <div class="stat-value">${{Math.round(stats.median)}}</div>
                    <div class="stat-label">Median (days)</div>
                </div>
                <div class="stat-card">
                    <div class="stat-value">${{stats.mean.toFixed(1)}}</div>
                    <div class="stat-label">Mean (days)</div>
                </div>
                <div class="stat-card">
                    <div class="stat-value">${{stats.p25}}</div>
                    <div class="stat-label">P25 (days)</div>
                </div>
                <div class="stat-card">
                    <div class="stat-value">${{stats.p75}}</div>
                    <div class="stat-label">P75 (days)</div>
                </div>
                <div class="stat-card">
                    <div class="stat-value">${{stats.p90}}</div>
                    <div class="stat-label">P90 (days)</div>
                </div>
            `;
        }}

        function updateCharts() {{
            const data = filterData();
            const stats = computeStats(data);
            updateStats(stats);

            const binSize = parseInt(document.getElementById('binSize').value);
            const durations = data.map(d => d.duration_days);

            // Histogram
            const histTrace = {{
                x: durations,
                type: 'histogram',
                xbins: {{ size: binSize }},
                marker: {{
                    color: 'rgba(37, 99, 235, 0.7)',
                    line: {{ color: 'rgba(37, 99, 235, 1)', width: 1 }}
                }},
                hovertemplate: 'Duration: %{{x}} days<br>Count: %{{y}}<extra></extra>'
            }};

            const histLayout = {{
                title: 'Duration Distribution',
                xaxis: {{
                    title: 'Duration (trading days)',
                    dtick: binSize * 2
                }},
                yaxis: {{ title: 'Frequency' }},
                bargap: 0.05,
                shapes: stats ? [
                    {{ type: 'line', x0: stats.median, x1: stats.median, y0: 0, y1: 1, yref: 'paper', line: {{ color: 'red', width: 2, dash: 'dash' }} }},
                    {{ type: 'line', x0: stats.p90, x1: stats.p90, y0: 0, y1: 1, yref: 'paper', line: {{ color: 'orange', width: 2, dash: 'dot' }} }}
                ] : [],
                annotations: stats ? [
                    {{ x: stats.median, y: 1, yref: 'paper', text: 'Median', showarrow: false, yanchor: 'bottom' }},
                    {{ x: stats.p90, y: 1, yref: 'paper', text: 'P90', showarrow: false, yanchor: 'bottom' }}
                ] : []
            }};

            Plotly.newPlot('histogram', [histTrace], histLayout, {{ responsive: true }});

            // Box plot by market cap
            const marketCaps = ['Mega', 'Large', 'Mid', 'Small'];
            const boxTraces = marketCaps.map(cap => {{
                const capData = data.filter(d => d.market_cap_tier === cap);
                return {{
                    y: capData.map(d => d.duration_days),
                    name: cap,
                    type: 'box',
                    boxmean: true
                }};
            }});

            const boxLayout = {{
                title: 'Duration by Market Cap Tier',
                yaxis: {{ title: 'Duration (trading days)' }},
                showlegend: false
            }};

            Plotly.newPlot('boxplot', boxTraces, boxLayout, {{ responsive: true }});
        }}

        // Initial render
        updateCharts();
    </script>
</body>
</html>
"""


def load_analysis_data(input_path: Path) -> dict[str, Any]:
    """Load analysis JSON data."""
    with open(input_path) as f:
        return json.load(f)


def generate_sector_options(downtrends: list[dict]) -> str:
    """Generate HTML options for sector dropdown."""
    sectors = sorted(set(d.get("sector", "Unknown") for d in downtrends))
    return "\n".join(f'                    <option value="{s}">{s}</option>' for s in sectors)


def generate_html(data: dict[str, Any]) -> str:
    """Generate the HTML visualization."""
    params = data.get("parameters", {})
    summary = data.get("summary", {})
    downtrends = data.get("downtrends", [])

    sector_options = generate_sector_options(downtrends)

    html = HTML_TEMPLATE.format(
        analysis_date=data.get("analysis_date", "Unknown")[:10],
        lookback_years=params.get("lookback_years", "?"),
        total_downtrends=summary.get("total_downtrends", 0),
        peak_window=params.get("peak_window", 20),
        min_depth=params.get("min_depth_pct", 5.0),
        sector_options=sector_options,
        downtrends_json=json.dumps(downtrends),
    )

    return html


def find_latest_json(input_pattern: str, output_dir: Path) -> Path | None:
    """Find the latest matching JSON file."""
    if "*" in input_pattern:
        # Glob pattern
        base_dir = Path(input_pattern).parent
        pattern = Path(input_pattern).name

        if not base_dir.exists():
            base_dir = output_dir

        matches = sorted(base_dir.glob(pattern), reverse=True)
        return matches[0] if matches else None
    else:
        # Direct path
        path = Path(input_pattern)
        return path if path.exists() else None


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate interactive HTML histogram from downtrend analysis"
    )
    parser.add_argument(
        "--input",
        default="reports/downtrend_analysis_*.json",
        help="Input JSON file or glob pattern (default: reports/downtrend_analysis_*.json)",
    )
    parser.add_argument(
        "--output-dir",
        type=str,
        default="reports",
        help="Output directory for HTML file (default: reports)",
    )

    args = parser.parse_args()

    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    # Find input file
    input_path = find_latest_json(args.input, output_dir)
    if not input_path:
        print(f"Error: No input file found matching '{args.input}'", file=sys.stderr)
        sys.exit(1)

    print(f"Loading data from: {input_path}")

    # Load and process data
    data = load_analysis_data(input_path)
    html_content = generate_html(data)

    # Write output
    timestamp = datetime.now().strftime("%Y-%m-%d_%H%M%S")
    output_path = output_dir / f"downtrend_histogram_{timestamp}.html"

    output_path.write_text(html_content, encoding="utf-8")
    print(f"HTML visualization saved to: {output_path}")


if __name__ == "__main__":
    main()
